name: Python CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install adbutils
      run: pip install adbutils

    - name: Install numpy
      run: pip install numpy

    - name: Install opencv
      run: pip install opencv-python

    - name: Install pillow
      run: pip install pillow

    - name: install pyinstaller
      run: pip install pyinstaller

    - name: Build EXE
      run: pyinstaller --onefile app.py

    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      with:
       tag: v1.0.0
       name: Emulator App v1.0.0
       artifacts: dist/app.exe
       makeLatest: true


    - name: Deploy project
      run: |
        echo "Deploying application..."
